#!/usr/bin/python3

# avax-python : Python tools for the exploration of the Avalanche AVAX network.
#
# Documentation at https://crypto.bi

"""

Copyright © 2021 ojrdev

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""

# --#--#--


# Print out AVAX private keys for a given secret phrase. 
# Use firstHdKeyEncoded to log into wallet.avax.network

# NOTE: A standard mnemonic phrase AVAX wallet would show you the address derived from firstHdKey
#
#       If you use firstHdKey or firstHdKeyEncoded to log into wallet.avax.network, you'll see the same address 
#       as the first generated address on the equivalent HD wallet. 

# Usage: private_key_from_mnemonic.py <phrase> 


import sys
from mnemonic import Mnemonic
from avaxpython.wallet import generator, BIP32
from avaxpython.wallet import Config as WalletConfig
from avaxpython import Config
from bip_utils import Bip32
import cb58ref
import json

sample_wallet = next(generator.generate(1, Config.KEY_SIZE))
word_length = len(sample_wallet.split(" "))

if len(sys.argv) != word_length+1:
    print("Invalid phrase length provided. Got {} expected {}.".format(len(sys.argv)-1, word_length))
    exit(1)

seed = Mnemonic("english").to_seed(" ".join(sys.argv[1:]), passphrase="")

masterHdKey = Bip32.FromSeed(seed)
accountHdKey = Bip32.FromSeedAndPath(seed, WalletConfig.AVA_ACCOUNT_PATH)

# the first private key generated by an HD wallet seeded from this mnemonic phrase
firstHDKey = BIP32.derive_master_key(accountHdKey, '0/0')

masterKey = masterHdKey.PrivateKey().Raw().ToBytes()
accountKey = accountHdKey.PrivateKey().Raw().ToBytes()
firstKey = firstHDKey.PrivateKey().Raw().ToBytes()

masterKeyEncoded = "PrivateKey-{}".format(cb58ref.cb58encode(masterKey))
accountKeyEncoded = "PrivateKey-{}".format(cb58ref.cb58encode(accountKey))
firstKeyEncoded = "PrivateKey-{}".format(cb58ref.cb58encode(firstKey))

output = {
    'masterHdKeyEncoded' : masterKeyEncoded,
    'accountHdKeyEncoded' : accountKeyEncoded,
    'masterHdKey' : masterKey.hex(),
    'accountHdKey' : accountKey.hex(),
    'firstHdKey' : firstKey.hex(),
    'firstHdKeyEncoded' : firstKeyEncoded,
    'seed': seed.hex()
}

print(json.dumps(output))
