# avax-python : Python tools for the exploration of the Avalanche AVAX network.
#
# Documentation at https://crypto.bi

"""

Copyright © 2021 ojrdev

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""

# --#--#--


# Generates the Python client API from spec2py AST

import spec2py
from datetime import datetime
from pprint import pprint

API_META_FILE = "apimeta.py"


def write_apimeta(api):    
    nowstr = str(datetime.now())
    lpe = list_packages_endpoints(api)
    dikt = spec2py.render_dict(api)
    header = get_header()
    with open(API_META_FILE, "w+") as f:
        f.write(header)
        f.write("\n")
        f.write("# Auto generated by generate_api.py\n")
        f.write("# On {}\n".format(nowstr))
        f.write("\n\n")
        f.write("api_endpoints = ")
        pprint(lpe, f)
        f.write("\n\n")
        f.write("api_meta = ")
        pprint(dikt, f)
        f.close()


def list_packages_endpoints(api):

    pe = {}

    for endpoint in api.endpoints:
        for mth in endpoint.methods:        
            pe[mth.package] = endpoint.endpoint

    return pe


def get_header():

    header = ""

    with open(__file__, "r") as f:
        lin = f.readline()
        while len(lin.strip()) > 0:
            header += lin
            lin = f.readline()

    return header


if __name__ == "__main__":
    api = spec2py.parse_api(spec2py.SPEC_FILE, spec2py.GRAMMAR_FILE)
    write_apimeta(api)    